### ISSUE TITLE
#1576 : planning, wireframing, tasking

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/firstfive#1]
### description
plan the layout, structure, and content type of the platforms main feature set. Including a homepage, catalog, and checkout page. The wireframing and planning will outline how the basic functionality components and pages will look ; everything from navigating and browsing our collections to placing orders on a checkout screen.

### requirement(s) 

- wireframe documents basic pages and describes their functionality.
- can easily see structure and layout of platform and identify the basic subsections. 

### subtask(s)

- [ ] define basic platform functionality
- [ ] wireframing for basic feature set
- [ ] breakdown features and distribute as tasks

### link(s)
[https://www.behance.net/gallery/147920509/10-Exchange](inspo)
